name: run-tests

on: [ push, pull_request ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ 8.2, 8.3, 8.4 ]
                laravel: [ 11.*, 12.* ]
                include:
                    -   laravel: 11.*
                        testbench: 9.*
                    -   laravel: 12.*
                        testbench: 10.*
        
        name: Laravel ${{ matrix.laravel }} + PHP ${{ matrix.php }}
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@2.9.0
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: xdebug

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                    composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
                    composer update --prefer-dist --no-interaction

            -   name: Execute tests
                run: composer run test
